### PR TITLE
Add default keybinding cmd+backspace=esc:w for macOS

### PR DESCRIPTION
**Pull request by korayfeyzula**
regarding https://github.com/ghostty-org/ghostty/issues/3646

### CODE REVIEW

**Comment by mitchellh** [comment]
Looks good, I just want to study a bit more on which is correct.

**Comment by Koray08** [comment]
`\x15` seems to be universally accepted across terminals

**Comment by vr7bd** [comment]
Just updated to 1.0.1. and it doesn't seem to be working
I reverted back my config to `keybind = super+backspace=text:\x15`(working) which the code seems to be doing
Maybe something is missing?

**Comment by mitchellh** [comment]
This may have to be escaped. There's a discrepancy here. It worked on my system but I'll look into it.

**Comment by jinalskothari** [comment]
can confirm, does not clear line by default in 1.01 . suggested binging works.

**Comment by lilyball** [comment]
in 1.0.1 for me in fish shell with vi keybindings ⌘⌫ both clears the current line and switches from input mode to normal mode. Fish is telling me that the ⌘⌫ sequence emits <kbd>Esc</kbd>, <kbd>Ctrl</kbd>+<kbd>U</kbd>.

`ghostty +show-config` tells me that the keybinding in effect here is

```
keybind = super+backspace=esc:^U
```

That said, I might suggest that Ghostty actually skip the keybinding here and instead implement `-deleteToBeginningOfLine:`. Ghostty passes text input through the Cocoa text input system, and if the text input client implements this selector then the text input system will invoke it in response to ⌘⌫. The reason for doing it this way is users who customize the text input system via DefaultKeyBindings.dict will then get expected behavior if they rebind this action. I might recommend this approach for any other similar standard macOS text editing actions that you're trying to set up keybinds for. By implementing the standard text input selector for the action instead you'll play nicely with users who rebind this, and you'll also know if you do the selector that you haven't missed any potential alternative keybinds that are supposed to do the same thing.

You can run `plutil -p /System/Library/Frameworks/AppKit.framework/Resources/StandardKeyBinding.dict` to see the standard set of Cocoa text input keybinds, this will tell you all the selectors they invoke, though the selectors should probably all be found in the [`NSStandardKeyBindingResponding`  protocol](https://developer.apple.com/documentation/appkit/nsstandardkeybindingresponding).

**Comment by rrotter** [comment]
> in 1.0.1 for me in fish shell with vi keybindings ⌘⌫ both clears the current line and switches from input mode to normal mode. Fish is telling me that the ⌘⌫ sequence emits Esc, Ctrl+U.

That's the problem, the expected output is `^U`, not `esc:^U`. fish accepts either as equivalent, but `esc:^U` doesn't work on zsh, or rather, it would be an entirely different keyboarding that won't do anything unless something is mapped to it. `esc:^U` also does nothing on bash.

**Comment by DrewLandgraveCbsi** [comment]
> keybind = super+backspace=text:\x15

This worked for me on mac 1.0.1 using zsh

**Comment by seeker-3** [comment]
on version 1.0.1 for me. Out of the box

command+backspace did not work with zsh and bash

but it did work for

fish and cat

but putting this in my config `keybind = super+backspace=text:\x15`

makes it work for all 4.

I'm on sequoia 15.2

**Pull request merged**
