### PR TITLE
gtk: equalize on double clicking the split handle

### PR DESCRIPTION
**Pull request by luk1337**

### CODE REVIEW

**Comment by mitchellh** [comment]
There's no previous discussion to approve this work but this is fairly standard expected behavior in my opinion so I'll accept it once CI is green. The diff looks good.

**Comment by luk1337** [comment]
> There's no previous discussion to approve this work but this is fairly standard expected behavior in my opinion so I'll accept it once CI is green. The diff looks good.

can you restart it? I modified the commit msg.

**Comment by luk1337** [comment]
prettier check failed on github issue template, do you expect me to rebase the branch myself or it's ok?

**Comment by mitchellh** [comment]
No all good.

**Comment by LuoZhongYao** [comment]
By convention, double-clicking should select the word, triple-clicking should select the sentence, and for complex cases with both horizontal and vertical splits, the effect after equalizing is very poor, so I think this pull request is ill-considered and should be reverted.

**Pull request merged**
