### PR TITLE
shell-integration: automatic bash integration

### PR DESCRIPTION
**Pull request by jparise**
This change adds automatic bash shell detection and integration.

Unlike our other shell integrations, bash doesn't provide a built-in mechanism for injecting our ghostty.bash script into the new shell environment.

Instead, we start bash in POSIX mode and use the ENV environment variable to load our integration script, and the rest of the bash startup sequence becomes the responsibility of our script to emulate (along with disabling POSIX mode).

### CODE REVIEW

**Comment by akinomyoga** [comment]
The codes added in this PR seem to be a direct translation (i.e., replacing "kitty" with "ghostty") of [the one in kitty](https://github.com/kovidgoyal/kitty/blob/492ec3dfbf3be6f27603baabb5c2844f91436e04/shell-integration/bash/kitty.bash#L6-L59). However, Ghostty's license is the MIT license, which is incompatible with kitty's GPL-3.0. Wouldn't that be a problem?

**Comment by jparise** [comment]
> I also thought we rewrote the bash integration at one point to be clean room anyways. But maybe not. Cc @jparise

It was originally a lot more basic, but when we were working through earlier compatibility challenges, I incorporated the additional flags, etc. from kitty.

Now that we've worked out those integration issues, I think we could remove some of that script complexity and just not support automatic script injection in those (rare) scenarios (e.g. `--noprofile`), but that's a separate discussion.

This is some preexisting recognition that some of this file's logic comes from kitty:

https://github.com/ghostty-org/ghostty/blob/bf3597a519164b81ca86f205d657557fc23fa8b7/src/shell-integration/bash/ghostty.bash#L1-L3

... but that doesn't call out the license aspect like we do in the zsh script.

**Comment by akinomyoga** [comment]
Thank you for taking time to answer my question.

> The shell integration isn’t embedded or part of our binary

In my understanding, that is a *necessary* condition that the shell integration and the main binary are considered two separate programs, but that's not *sufficient* to claim they are separate. For example, consider a GPL-licensed project written in an interpreter programming language. If GPL only applies to a program compiled into a single binary, GPL doesn't make any sense for such a project.

What I wondered were the following two points:

The first is whether the shell integration is part of the Ghostty feature set or an external plug-in for Ghostty. To claim it is a separate product, we need to consider the shell integration *a plug-in* or *an extra feature*.

The second point is whether the "plug-in" establishes an [*intimate communication*](https://www.gnu.org/licenses/gpl-faq.html.en#GPLPlugins) with the main Ghostty process. By nature of the shell integration, once the shell-integration code is loaded in Bash, the instance of the shell integration continues to be inside Bash and establishes mutual communication with the main Ghostty process. This coupling seems stronger than the [*borderline case*](https://www.gnu.org/licenses/gpl-faq.html.en#GPLPlugins) invoking the plug-in and waiting for its final results.

- The part added by this PR just handles the initialization, but the latter part of `ghostty.bash` implements mutual communication, and it would be hard to claim the former and latter parts of a single file are two separate programs.
- Even in this case, it might be possible to claim that both Ghostty and the shell integration implement a public shell-integration protocol (including the injection part utilizing `ENV`) and make the shell-integration script replaceable with another implementation (such as `kitty.bash`) in the user configuration. But I'm not so sure about this.

Technically, even if the shell integration is not considered a separate program, we can continue to use the GPL-licensed code until the copyright holder contacts us. In this sense, it might not be urgent but I think it would be good to clarify the stance on those points.

> I also thought we rewrote the bash integration at one point to be clean room anyways. But maybe not. Cc @jparise

At least the codes merged in this PR are still present in the latest Ghostty. Actually, it's the other way around. I first found the shell-integration code in the latest version, and then I reached here after trying to find where to raise the discussion.

**Comment by akinomyoga** [comment]
Yeah, the borderline of GPL is always difficult. Thank you for sharing your thoughts.

**Pull request merged**
