### PR TITLE
gtk: don't use gtk_window_set_titlebar if adwaita is enabled but it's older than 1.4.0

### PR DESCRIPTION
**Pull request by jcollie**
Fix #4097

### CODE REVIEW

**Review by tristan957 — APPROVED** [review]
Thanks for fixing my mistake!

**Comment by tristan957** [comment]
It would be good to mention the discussion too.

**Comment by jcollie** [comment]
> It would be good to mention the discussion too.

Yeah, once I get confirmation from the folks in #4097 that this actually works for them I'll update the description with relevant info.

**Comment by mitchellh** [comment]
Failing CI is a flappy test. The rest looks good. Just advise when you want me to merge.

**Comment by jcollie** [comment]
OK, I've gotten two reports that this fixes the issue so it's ready to merge.

**Pull request merged**
